### ISSUE TITLE
Feature request: support for aliases

### ISSUE THREAD

**Issue by tlockney** [tailscale/golink#101]
Some of the go-link systems that I've used  in the past have supported aliases for a given link. I know it would be possible to just create multiple items using the same link, but ideally if a link gets updated, all the alternate names get updated at once.

**Comment by willnorris** [comment]
Pick one link to be the primary, and set that up.  Say:

```
go/bugs  =>  https://bugs.example.com
```

Then set up the aliases to point at the primary:

```
go/b  =>  /bugs
go/issues  =>  /bugs
go/bugz  =>  /bugs
```

They all resolve to the bug tracker, but only the main go/bugs link needs to be updated if it ever changes.

**Comment by willnorris** [comment]
There's other fun things you can do by chaining go links together like this that I wrote about recently: https://willnorris.com/2023/golinks-across-tailnets/

**Comment by tlockney** [comment]
Oh, perfect. I should have thought to try that. It seems almost TOO obvious in retrospect. Ha!

And, yeah, that post is going to help a lot! I had already looked into the templating and had a few ideas, but this gives me a lot more to work with. Thanks!
