### ISSUE TITLE
Feature request: option to disable HTTPS

### ISSUE THREAD

**Issue by tiesmaster** [tailscale/golink#107]
It was really awesome to see that HTTPS was getting added in #99, to resolve #29, which helps workflows for some people. However, I'd rather have HTTPS turned off. I've [configured my browser](https://github.com/tailscale/golink#firefox-configuration) to ignore the missing HTTPS, and don't use the [opensearch xml](https://github.com/tailscale/golink/issues/29#issuecomment-1347134470) feature. One of the downsides of having this turned on, is that golink needs to acquire a new cert on initial deployment, which takes time to get the service live (not a big problem, but also a bit annoying).

I know you can turn off HTTPS from the [Admin console](https://login.tailscale.com/admin/machines), which I did, as I don't use the HTTPS feature of Tailscale atm. However, I'd like to be able to turn this on in the future, and don't get golink breaking on this, which I'll have completely forgotten about in a couple of months.

Yeah, I know, I guess [XKCD 1172](https://xkcd.com/1172/) is applicable ;) Though, I am willing to contribute a PR, which I'd gladly do. Would you be willing to accept a PR to add support for a configuration flag to override this behavior?

**Comment by noncombatant** [comment]
Hello @tiesmaster! Sure, if you send a PR, we'll take a look. Thanks! :)
