### ISSUE TITLE
Add CLI resolver

### ISSUE THREAD

**Issue by bradfitz** [tailscale/golink#15]
If Tailscale's unavailable (e.g. you're on the wrong tailnet), it'd be nice as a backup to be easily expand go links from the backup JSON file, using the same templating.

Like:

```
$ go run github.com/tailscale/golink --resolve-from-backup=/path/to/backup.json go/meet/bar
http://meet.google.com/lookup/bar
```

cc @willnorris

**Comment by willnorris** [comment]
ooh, cool.  yeah, I like that.
