### ISSUE TITLE
FR: Ability to delete golinks

### ISSUE THREAD

**Issue by tycoonlover1359** [tailscale/golink#16]
Unless I'm missing something, I'd be great to have a way to delete golinks that are no longer needed. I've tried everything I can reasonably think of:

- Sending `DELETE` requests to `go/<name>+` (results in the server just responding with the details for the shortname);
- Sending `DELETE` requests to `go/<name>` (results in the server redirecting me to the destination);
- Appending `?action=delete` onto `go/<name>+` (results in 404)
- Even clearing one or both of the shortname and destination fields in the golink web editor (results in "please fill out this field")

**Comment by willnorris** [comment]
you're not missing anything :)  This has been on the mental backlog for a little while, but just never got implemented because we hadn't run into a strong need for it yet internally.  Definitely something we can add.
