### ISSUE TITLE
Possible trademark infringement?

### ISSUE THREAD

**Issue by sullivanmatt** [tailscale/golink#31]
IANAL.

The founder of https://golinks.io holds a number of U.S. trademarks related to the name "GO LINKS". If nobody has done so, it may be advisable to seek guidance from legal to avoid any sort of tiff with a product that offers exactly this functionality that is covered under existing U.S. trademarks.

**Comment by willnorris** [comment]
Thanks for the heads up.  Not really something we'd handle on GitHub, so I'll close the issue.
