### ISSUE TITLE
golink owner is getting mangled

### ISSUE THREAD

**Issue by dustin** [tailscale/golink#37]
I was trying to edit a link I made from my phone and it told me I wasn't the owner and [my address] was.  This was surprising.  I came back and looked from my computer and saw the same thing.

So I looked at another link that I'd made more recently and I saw that the owner was `tagged-devices`.

A possible workaround might be #18, but I'm very strongly advocating for this at work, so it might be good to have a better understanding of what's going on here.

**Comment by bradfitz** [comment]
Backing up a sec, the common misconception about tags (that likely applies here?) is that they're not meant to apply to humans. Once you tag a device in Tailscale, it loses all its human identity.

So perhaps what golink should do is prohibit the creation of golinks by tagged devices at all and say "Sorry tagged-device, golinks are for humans."

/cc @willnorris

**Comment by willnorris** [comment]
Oh yeah, that sounds like a pretty clear oversight.  Go links should only be owned by humans.  I'll test tomorrow.

**Comment by bradfitz** [comment]
And if any link was already created by a tagged-device, let any human take it over?

**Comment by willnorris** [comment]
That's actually interesting.. maybe we let tagged nodes create links (could be useful for some automated scenarios?), but always let humans override?

**Comment by bradfitz** [comment]
Also, hi @dustin! 👋

**Comment by dustin** [comment]
Awesome.  This explains another bit of confusion I had trying to get ssh working earlier.
