### ISSUE TITLE
How to update tailscale version

### ISSUE THREAD

**Issue by Mansarde** [tailscale/golink#41]
I wanted to build a Docker image with the most up to date Tailscale.
From what I could see it seems that `go.mod` is where I can define the Tailscale version.

It uses a pseudo-version, currently `v1.1.1-0.20221106050213-036334e91350`, which somehow maps to Tailscale `v1.33.0-dev20221229`.
But I didn't have any luck figuring out what pseudo-version I would have to set to update it to e.g. Tailscale v1.34.1

Could anyone give me a pointer as to how the specific Tailscale version is selected?

**Comment by willnorris** [comment]
You can update the tailscale version with:

```
go get -u tailscale.com
```

We will often build from HEAD, which is why this is a pseudo-version.  For that, you'd use `go get -u tailscale.com@main`.  I'll checkin an updated version here in a bit.

**Comment by Mansarde** [comment]
You mean execute that in the running container?
But how would I need to modify `go.mod` in the repo, so that I can build an image that already has the new Tailscale installed?
Usually I would assume I just change the `tailscale.com v1.1.1-0.20221106050213-036334e91350` to `tailscale.com v1.34.2`, but then I would not be using a pseudo-version that the comment in the file talks about.

How do I create an image with the latest Tailscale while still keeping a pseudo-version entry in the `go.mod` file?
I'm just confused as to how the pseudo-version is determined and maps to a particular real Tailscale version. 🤔

**Comment by willnorris** [comment]
the version of tailscale that golink uses has since been updated.
