### ISSUE TITLE
"sqlite is busy" error

### ISSUE THREAD

**Issue by dustin** [tailscale/golink#46]
I saw a sqlite busy error when attempting to follow a link earlier.  I suspect there may be some concurrency issues on writes that could use a retry.

I've not looked, but when I've had to do this kind of thing before, I had to bring my own lock and/or async writes (e.g., for updating counts where a failure doesn't lead to a real correctness problem).

I think you have to be kind of lucky to see the error in general, but it'd likely show up in a load test.

**Comment by willnorris** [comment]
Should be fixed by #59
