### ISSUE TITLE
Error installing on fly.io

### ISSUE THREAD

**Issue by heliostatic** [tailscale/golink#51]
The instructions for running on fly.io are currently failing at the deploy step:
```
==> Creating release
Error Could not find image "ghcr.io/tailscale/golink:main"
```
It _appears_ this may be related to a change in the way github actions are building docker images, per conversation on the fly.io forums:
https://community.fly.io/t/deploying-to-fly-via-github-action-failing/10171/19

And per that thread, the fix may be as simple as adding `provenance: false` to the build action

**Comment by willnorris** [comment]
I'm not completely sure what the implications of disabling provenance are.  I found that I was able to solve this on another project by [downgrading to buildx v0.9.1](https://github.com/willnorris/imageproxy/commit/f314cbfc8738cca4fdc968d392b751470c9b0c08), so I think I'll do that here for the time being.
