### ISSUE TITLE
Golinks giving build constraints error after update

### ISSUE THREAD

**Issue by lvendeville** [tailscale/golink#85]
Not sure if this is specific to my setup or a wider issue with some more common update. Running Ubuntu 22.04.3, and after a series of system/application updates I'm now getting the below error when trying to start the golinks service using the following Terminal command: 

TS_AUTHKEY="tskey-auth-{keygoeshere}" go run ./cmd/golink -sqlitedb golink.db
_____________________________________________________________________
imports github.com/tailscale/golink
	imports tailscale.com/tsnet
	imports tailscale.com/ipn/ipnlocal
	imports tailscale.com/wgengine
	imports tailscale.com/net/tstun
	imports gvisor.dev/gvisor/pkg/tcpip
	imports gvisor.dev/gvisor/pkg/atomicbitops
	imports gvisor.dev/gvisor/pkg/state
	imports gvisor.dev/gvisor/pkg/state/wire
	imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /home/administrator/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20221203005347-703fd9b7fbc0/pkg/gohacks
_____________________________________________________________________
Also a Linux complete noob, but I tried running "./update-flake.sh" and "go clean -modcache" which both completed -though the error remains.

**Comment by bradfitz** [comment]
It's not clear what you're doing. You omitted any info on what command you ran to get those errors.

**Comment by lvendeville** [comment]
Apologies. I've updated the original description to include that it happens when I try to run "TS_AUTHKEY="tskey-auth-{keygoeshere}" go run ./cmd/golink -sqlitedb golink.db" in Terminal to start providing the golinks service.

**Comment by bradfitz** [comment]
If you updated the golinks code to a newer version, it's likely you need a newer version of Go now. Do you have Go 1.21?

**Comment by lvendeville** [comment]
Was running Go 1.20, upgraded to 1.21 and was getting the same error. Downloaded the golinks newest ZIP file and tried to start the service in the new folder, and it started without issue (though I'll need to redo the actual links again).

**Comment by bradfitz** [comment]
Sounds like you figured it out. Fwiw, you can move the database file over and not need to remake the links.
