### ISSUE TITLE
Update your tailscale version

### ISSUE THREAD

**Issue by mickeydarrenlau** [tailscale/golink#96]
![image](https://github.com/tailscale/golink/assets/62752664/4bbb90ff-4f63-40ac-8720-2b1dc6af9399)

```[tasklist]
### Tasks
- [ ] https://github.com/tailscale/golink/pull/105
```

**Comment by mickeydarrenlau** [comment]
I think you all should really upgrade now
![image](https://github.com/tailscale/golink/assets/62752664/759d7b17-30bf-4f99-a285-89adab4b90b7)

**Comment by willnorris** [comment]
this has since been updated
